import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';
import { AppProvider } from '@/context/App.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NewCo Gym',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Suspense>{children}</Suspense>
        </AppProvider>
      </body>
    </html>
  );
}
